In [1]:
import numpy as np
from scipy import linalg

In [5]:
y = np.array([[15],[28],[42],[64],[50],[90],[58],[8],[54]], dtype = np.float)
x = np.array([[1,2],[1,3],[1,5],[1,13],[1,8],[1,16],[1,11],[1,1],[1,9]], dtype = np.float)
print("y=\n",y)
print("\nx=\n",x)

xT = np.transpose(x)
print("\nxT =\n",xT)

xTx = np.array(xT.dot(x))
print("\nxT.x=\n",xTx)

xTx_1 = np.linalg.inv(xTx)
print("\n(xT.x)^-1=\n",xTx_1)

xTx_1_xT = np.array(xTx_1.dot(xT))
print("\n(xT.x)^-1.xT=\n",xTx_1_xT)

xTx_1_xT_y = np.array(xTx_1_xT.dot(y))
print("\n(xT.x)^-1.xT.y=\n",xTx_1_xT_y)

y=
 [[15.]
 [28.]
 [42.]
 [64.]
 [50.]
 [90.]
 [58.]
 [ 8.]
 [54.]]

x=
 [[ 1.  2.]
 [ 1.  3.]
 [ 1.  5.]
 [ 1. 13.]
 [ 1.  8.]
 [ 1. 16.]
 [ 1. 11.]
 [ 1.  1.]
 [ 1.  9.]]

xT =
 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  3.  5. 13.  8. 16. 11.  1.  9.]]

xT.x=
 [[  9.  68.]
 [ 68. 730.]]

(xT.x)^-1=
 [[ 0.37512847 -0.03494347]
 [-0.03494347  0.00462487]]

(xT.x)^-1.xT=
 [[ 0.30524152  0.27029805  0.2004111  -0.07913669  0.09558068 -0.18396711
  -0.00924974  0.34018499  0.0606372 ]
 [-0.02569373 -0.02106886 -0.01181912  0.02517986  0.0020555   0.03905447
   0.01593011 -0.0303186   0.00668037]]

(xT.x)^-1.xT.y=
 [[9.18088386]
 [4.7995889 ]]
